### ISSUE TITLE
bintray is being sunset

### ISSUE THREAD

**Issue by foresmac** [jakubriegel/kotlin-shell#13]
Bintray is going away as of May 1st: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Is it possible to update the docs to indicate how to include `kotlin-shell` assuming bintray is not available?

**Comment by jakubriegel** [comment]
I'll migrate from Bintray to GitHub packages in the following days

**Comment by jakubriegel** [comment]
I've migrated the project to GitHub packages (#14). Link to artifacts: https://github.com/jakubriegel?tab=packages&repo_name=kotlin-shell

@foresmac can you please confirm that it works for you? If yes, I will merge and publish package from master

**Comment by jakubriegel** [comment]
PR merged. Kotlin Shell is now available via GitHub packages

**Comment by foresmac** [comment]
Thanks! 👍
