### ISSUE TITLE
publish to Maven central

### ISSUE THREAD

**Issue by cvmocanu** [jakubriegel/kotlin-shell#16]
Publish this project to Maven central, since this is a lot more convenient to use than custom repos.

Information on requirements (pom metadata, GPG signing, etc.) here: https://central.sonatype.org/publish/publish-guide/
See an example of how to publish to Maven central from Gradle here: https://github.com/testerum/testerum-api/tree/gradle

**Comment by jakubriegel** [comment]
Will take a look on that

**Comment by jakubriegel** [comment]
Sorry, I don't have space to do it now. 

If you want, you can prepare PR with configuration for publishing

**Comment by martinbonnin** [comment]
Pull request there: https://github.com/jakubriegel/kotlin-shell/pull/20

See https://oss.sonatype.org/content/repositories/netmbonnin-1083 for a preview of the artifacts (don't mind the group id).

It requires 4 environment variables:

* `SONATYPE_NEXUS_USERNAME`
* `SONATYPE_NEXUS_PASSWORD`
* `GPG_PRIVATE_KEY` (armoured, in-memory GPG key)
* `GPG_PRIVATE_KEY_PASSWORD`

The Github Action yaml files will need updating as well. I can try to do that, albeit won't really be able to test until next release and requires the variables to be in the environment.

Might be worth changing the groupId for faster verification on sonatype too? Not sure. In all cases, let me know if I can help with anything else.

**Comment by jakubriegel** [comment]
Thanks for contribution! 🥳  I've created a ticket for getting group id on Sonatype (https://issues.sonatype.org/browse/OSSRH-71319). The next few I will be away-from-keyboard, but they say it may take some to create the account for me. 
After successful registration on Sonatype I'll work on Action for publishing. My plan is to have it published to mvn on the beginning of next week.

**Comment by martinbonnin** [comment]
Awesome 😃 ! Thanks !!! 

PS: validation should be pretty fast these days, I've heard cases were accounts were validated in less than 1h

**Comment by jakubriegel** [comment]
I've added credentials and merged the pr. Publishing works (https://github.com/jakubriegel/kotlin-shell/runs/3180057146) 😄 Unfortunately some checks failed during synchronizing the artifact to Maven Central. Will take a look on that

**Comment by jakubriegel** [comment]
It is published! 🥳 https://s01.oss.sonatype.org/#nexus-search;quick~kotlin-shell 
Can you confirm that it works for you? @martinbonnin @cvmocanu

**Comment by jakubriegel** [comment]
https://repo1.maven.org/maven2/eu/jrie/jetbrains/

**Comment by martinbonnin** [comment]
Works for me 🎉 

I can include it in scripts with:

```
@file:DependsOn("eu.jrie.jetbrains:kotlin-shell-core:0.2.1")
```

Might be worth updating the readme to point to maven central?

**Comment by jakubriegel** [comment]
Sure! I've updated the readme

**Comment by jakubriegel** [comment]
Everything is done now 😄 @cvmocanu and @martinbonnin thank you for your contribution!
