### ISSUE TITLE
Published package info is incorrect 

### ISSUE THREAD

**Issue by brizzbuzz** [jakubriegel/kotlin-shell#18]
Hey, very cool project.

This page https://github.com/jakubriegel/kotlin-shell/packages/765107 incorrectly lists `groupId` as `kotlin-shell-core.eu.jrie.jetbrains` where it should be `eu.jrie.jetbrains`

**Comment by jakubriegel** [comment]
Did #16 fix it? @rgbrizzlehizzle

**Comment by brizzbuzz** [comment]
Doesn't look like it for github, but on maven central it looks correct which is much more important, i would assume 99% of devs will download it from there :) Feel free to close if you'd like
