### ISSUE TITLE
How can I get the output of a command?

### ISSUE THREAD

**Issue by elect86** [jakubriegel/kotlin-shell#25]
As titled, sorry if this may sound dumb, but I'm looking at parsing manually specific commands outputs.

**Comment by jakubriegel** [comment]
Hi!
Look like related to #21

**Comment by elect86** [comment]
Something like this?
```
    val out = ByteArrayOutputStream()
    pipeline { "ls".process() pipe out }
    println(out)
```
Can I be sure there won't be any race condition because of the Coroutine?
Is there a simpler way?

**Comment by jakubriegel** [comment]
It will work fine and it is the only supported way
