### ISSUE TITLE
Interpolation of Kotlin variables not working?

### ISSUE THREAD

**Issue by helpermethod** [jakubriegel/kotlin-shell#26]
Hi!

First of all, great project, exactly what I was looking for!

I'm currently writing a script which delegates to git to create a commit / branch and corresponding merge request. This seems to work fine, except for the commit itself

```kt
shell {
    "git checkout -b silencer/exclude-${packageName.replace(':', '_')}"()
    "git add renovate.json"()
    "git -c user.name=silencer -c user.email= commit -m 'chore(dependency-updates): Exclude $packageName from $groupName'"()
    "git push -o merge_request.create"()
}
```

Somehow the interpolation in the commit message is not working, the string `'chore(dependency-updates): Exclude $packageName from $groupName'` is split into multiple words it seems. Is this a bug or an error on my side?

Thanks in advance!

**Comment by helpermethod** [comment]
Okay, it seems the interpolation is not the problem. This call also seems to be problematic:

    "git commit -m 'chore(dependency-updates): Exclude packageName from groupName'"()
    
 For some reason is split into multiple tokens
 
     -m 'chore(dependency-updates):
     Exclude
     packageName
     from
     groupName'

So the single quotes in `'chore(dependency-updates): Exclude packageName from groupName'` seem to be the problem.

**Comment by helpermethod** [comment]
Answering my own question: You need to use `systemProcess`

```
 systemProcess {
    cmd { "git" withArgs listOf("commit", "-m", "chore(dependency-updates): Exclude $groupName from $packageName") }
 }()
```

**Comment by jakubriegel** [comment]
Thanks for engagement!
